Grocery/urls.py
from django.contrib import admin
from django.urls import path, include

from Grocery import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('grocery/', include('grocery_list.urls'), name="grocery")
]

grocery_list/urls.py
from django.urls import path

from grocery_list import views

app_name = 'grocery'

urlpatterns = [
    path('', views.GroceryListView.as_view(), name="index"),
    path('<int:pk>/update', views.GroceryView.as_view(), name="update"),
    path('<int:pk>/delete', views.GroceryDeleteView.as_view(), name="delete"),
    path('create', views.GroceryCreateView.as_view(), name="create"),
]

grocery_list/models.py
from django.contrib.auth.models import User
from django.db import models

ITEM_STATUS = (
    (1, "Bought"),
    (2, "NOT AVAILABLE"),
    (3, "PENDING")
)


class GroceryList(models.Model):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    item_name = models.CharField(max_length=30)
    item_quantity = models.CharField(max_length=20)
    item_status = models.IntegerField(choices=ITEM_STATUS, default=3)
    date = models.DateField()

    def __str__(self):
        return self.item_name + self.item_quantity

grocery_list/forms.py
from django.forms import ModelForm, Select, DateInput, SelectDateWidget, TextInput, Form

from grocery_list.models import GroceryList


class DateTypeInput(DateInput):
    input_type = 'date'


class GroceryListForm(ModelForm):
    class Meta:
        model = GroceryList
        fields = "__all__"
        exclude = ['user']
        widgets = {
            "item_status": Select(attrs={'class': 'form-control'}),
            "date": DateTypeInput(attrs={'class': 'form-control'}),
            "item_quantity": TextInput(attrs={'class': 'form-control'}),
            "item_name": TextInput(attrs={'class': 'form-control'})
        }

    def save(self, user=None):
        user_profile = super(GroceryListForm, self).save(commit=False)
        if user:
            user_profile.user = user
        user_profile.save()
        return user_profile

Grocery/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import FormView

from Grocery.login import LoginForm


class LoginView(FormView):
    form_class = LoginForm
    template_name = "login.html"

    def get(self, request, **kwargs):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('grocery:index')
        return render(request, self.template_name, {"form": form})


class RegisterView(FormView):
    form_class = LoginForm
    template_name = 'signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.create_user(username=username, password=password)
            user.save()
            login(request, user)
            return redirect('grocery:index')


class LogoutView(View):

    def get(self, request):
        logout(request)
        print("logged out successfully")
        return redirect('login')

grocery_list/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView, DeleteView, CreateView

from grocery_list.forms import GroceryListForm
from grocery_list.models import GroceryList


class GroceryListView(ListView):
    template_name = 'grocery_list/index.html'
    context_object_name = "grocery_list"

    def get_queryset(self):
        print(self.request.user)
        return GroceryList.objects.filter(user=self.request.user)

    def post(self, request):
        form_date = request.POST.get("date")
        grocery_list = GroceryList.objects.filter(user=self.request.user, date=form_date)
        return render(request, self.template_name, {"grocery_list": grocery_list})


class GroceryView(FormView):
    form_class = GroceryListForm
    template_name = 'grocery_list/update.html'

    def get(self, request, **kwargs):
        instance = GroceryList.objects.get(pk=kwargs['pk'])
        form = self.form_class(instance=instance)
        return render(request, self.template_name, {"form": form})

    def form_valid(self, form):
        form.save()
        return redirect('grocery:index')

    def post(self, request, *args, **kwargs):
        instance = GroceryList.objects.get(pk=kwargs['pk'])
        form = self.form_class(request.POST, instance=instance)
        if form.is_valid():
            form.save(self.request.user)
            form.save()
            return redirect('grocery:index')
        return render(request, self.template_name, {"form": form})


class GroceryDeleteView(DeleteView):
    model = GroceryList
    success_url = reverse_lazy('grocery:index')


class GroceryCreateView(CreateView):
    model = GroceryList
    template_name = 'grocery_list/update.html'
    form_class = GroceryListForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(self.request.user)
            form.save()
            return redirect('grocery:index')
        return render(request, self.template_name, {"form": form})

grocery_list/templates/grocery_list/index.html
{% extends "base.html" %}
{% block title %}View List{% endblock %}
{% load static %}
{% block extra_header_links %}
    <link rel="stylesheet" href="{% static 'grocery_list/css/style.css' %}">
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <!-- top -->
        <div class="row">
            <div class="col-lg-6">
                <h1>View Grocery List</h1>
            </div>
            <div class="col-lg-6 float-right">
                <div class="row">
                    <form method="post" enctype="multipart/form-data" class="col-lg-8">
                        {% csrf_token %}
                        <div class="col-lg-8">
                            <!-- Date Filtering-->
                            <input type="date" class="form-control" name="date">
                        </div>
                        <div class="col-lg-4" style="margin: 10px 0">
                            <input type="submit" class="btn btn-info" value="filter">
                        </div>
                    </form>
                    <div class="col-lg-4">
                        <button type="button" class="btn btn-danger"><a href="{% url 'logout' %}" class="btn-logout">logout</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- // top -->
        <!-- Grocery Cards -->
        <div class="create-container">
            <a href="{% url 'grocery:create' %}" class="btn-create">Create</a>
        </div>
        <div class="row mt-4">
            <!--- -->
            <!-- Loop This -->
            {% for grocery in grocery_list %}
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ grocery.item_name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ grocery.item_quantity }}</h6>
                            {% if grocery.item_status == 3 %}
                                <p class="text-info">{{ grocery.get_item_status_display }}</p>
                            {% elif grocery.item_status == 2 %}
                                <p class="text-danger">{{ grocery.get_item_status_display }}</p>
                            {% elif grocery.item_status == 1 %}
                                <p class="text-success">{{ grocery.get_item_status_display }}</p>
                            {% endif %}
                        </div>

                        <div class="flex-container">
                            <button type="button" class="btn btn-dark card-link-delete">
                                <a href="{% url "grocery:update" grocery.pk %}">Update</a>
                            </button>
                            <form method="post" action="{% url "grocery:delete" grocery.pk %}" class="delete-form">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

grocery_list/templates/grocery_list/update.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update List</title>
        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'grocery_list/css/style.css' %}">
    </head>
    <body>
        <div class="container mt-5">
            <h1>Update Grocery List</h1>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Item Name</label>
                    {{ form.item_name }}
                </div>
                <div class="form-group">
                    <label>Item Quantity</label>
                    {{ form.item_quantity }}
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    {{ form.item_status }}
                </div>
                <div class="form-group">
                    <label>Date</label>
                    {{ form.date }}
                </div>
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-danger">
                </div>
            </form>
        </div>
    </body> 
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Load the path to your static files-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}SE{% endblock %}</title>
    {% load static %}
    {% block extra_header_links %}{% endblock %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block body %}
{% endblock %}

{% block external_script %}{% endblock %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% load static %}
{% block extra_header_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'grocery_list/css/login.css' %}">
{% endblock %}
{% block body %}
    <div class="login-wrap"
         style="{bacground-image: url(https://images.theconversation.com/files/282104/original/file-20190701-105182-1q7a7ji.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=900.0&fit=crop); background-repeat: no-repeat;position: center}">
        <div class="login-html">
            <h3 class="form-head">Sign IN</h3>
            <div class="login-form">
                <form enctype="multipart/form-data" method="post" class="login">
                    {% csrf_token %}
                        {% for field in form %}
                            <div class="group">
                                <span class="text-danger small">{{ field.errors }}</span>
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Sign In">
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <a href="{% url 'register' %}" class="register-link">Register</a>
                        </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block external_script %}
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block title %}Signup{% endblock %}
{% load static %}
{% block extra_header_links %}
    <link rel="stylesheet" type="text/css" href="{% static 'grocery_list/css/login.css' %}">
{% endblock %}
{% block body %}
    <div class="login-wrap"
         style="{bacground-image: url(https://images.theconversation.com/files/282104/original/file-20190701-105182-1q7a7ji.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=900.0&fit=crop); background-repeat: no-repeat;position: center}">
        <div class="login-html">
            <h2 class="form-head">Sign UP</h2>
            <div class="login-form">
                <form enctype="multipart/form-data" method="post" class="login" action="{% url 'register' %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="group">
                            <span class="text-danger small">{{ field.errors }}</span>
                            {{ field.label_tag }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <div class="group">
                        <input type="submit" class="button" value="Sign Up">
                    </div>
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <label for="tab-1"><a href="{% url 'login' %}" class="register-link">Already Member?</a></label>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block external_script %}
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
{% endblock %}